name: Aliyun Signin
author: Yumu152068
description: 'AliyunDrive signin automatically'

inputs:
  REFRESH_TOKENS:
    description: 'AliyunDrive refresh tokens'
    required: true

  GP_TOKEN:
    description: 'Github personal access token'
    required: false
    default: ''

  PUSH_TYPES:
    description: 'Push types for signin result'
    required: false
    default: ''

  WEBHOOK_URL:
    description: 'Webhook url'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - id: version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: Yumu152068/aliyun-auto-signin
        excludes: prerelease, draft
        token: ${{ inputs.GP_TOKEN }}
    - name: Download
      shell: bash
      run: |
        wget https://github.com/Yumu152068/aliyun-auto-signin/archive/refs/tags/${{ steps.version.outputs.release }}.zip -O release.zip
        rm -rf release
        unzip release.zip -d release
        rm release.zip
    - name: Run
      shell: bash
      run: |
        cd release
        cd $(ls -dt */|head -1 )
        pip install -r requirements.txt
        python app.py -a
      env:
        REFRESH_TOKENS: ${{ inputs.REFRESH_TOKENS }}
        GP_TOKEN: ${{ inputs.GP_TOKEN }}
        GITHUB_REPOS: ${{ github.repository }}
        PUSH_TYPES: ${{ inputs.PUSH_TYPES }}
        WEBHOOK_URL: ${{ inputs.WEBHOOK_URL }}

branding:
    icon: 'check-circle'
    color: 'orange'
